"""
OAuth Authentication Port (OIDC-based).

This port defines the interface for OAuth 2.0 / OIDC authentication providers.
Based on standard OIDC flows to ensure provider independence.

Adapters:
- FirebaseAuthAdapter (MVP) - src/adapters/firebase_auth_adapter.py
- Future: AWS Cognito, Okta, Auth0, Azure AD

RFC: docs/10_rfcs/MULTI_TENANT_OAUTH_RFC.md
"""
from abc import ABC, abstractmethod
from typing import Optional, Dict, Any
from datetime import datetime
from pydantic import BaseModel


class TokenClaims(BaseModel):
    """
    Claims extracted from OAuth token (JWT).
    Based on OIDC standard claims.
    """
    sub: str  # Subject - unique user identifier from provider
    iss: str  # Issuer - provider identifier (e.g., "https://securetoken.google.com/project-id")
    aud: str  # Audience - client ID
    exp: datetime  # Expiration time
    iat: datetime  # Issued at time

    # Optional OIDC standard claims
    email: Optional[str] = None
    email_verified: Optional[bool] = None
    name: Optional[str] = None
    picture: Optional[str] = None

    # Provider-specific claims (stored as-is)
    custom_claims: Dict[str, Any] = {}


class OAuthTokens(BaseModel):
    """
    OAuth tokens received after authorization code exchange.
    """
    access_token: str
    refresh_token: Optional[str] = None
    id_token: str  # JWT with user claims
    expires_in: int  # Seconds until access_token expires
    token_type: str = "Bearer"


class OAuthUserInfo(BaseModel):
    """
    User information from OAuth provider's UserInfo endpoint.
    Combines OIDC standard fields + provider-specific metadata.
    """
    # OIDC standard fields
    sub: str  # Subject identifier (unique user ID)
    email: Optional[str] = None
    email_verified: Optional[bool] = None
    name: Optional[str] = None
    given_name: Optional[str] = None
    family_name: Optional[str] = None
    picture: Optional[str] = None
    locale: Optional[str] = None

    # Provider-specific metadata (stored in auth_metadata)
    provider_metadata: Dict[str, Any] = {}


class AuthPort(ABC):
    """
    OAuth Authentication Port (OIDC-based).

    Provider-agnostic interface for OAuth 2.0 / OIDC authentication.
    Implementations must handle provider-specific details internally.

    Flow:
    1. User clicks "Sign in with Google" → get_authorization_url()
    2. User authorizes → OAuth provider redirects with code
    3. Backend receives code → exchange_code_for_tokens()
    4. Backend verifies token → verify_token()
    5. Backend fetches user info → get_user_info()
    """

    @abstractmethod
    def get_provider_name(self) -> str:
        """
        Return provider identifier used in external_user_id prefix.

        Examples: "firebase", "cognito", "okta", "auth0"
        Used to construct external_user_id: "{provider}|{sub}"
        """
        pass

    @abstractmethod
    def get_authorization_url(self, state: str, redirect_uri: str) -> str:
        """
        Generate OAuth authorization URL for user redirect.

        Args:
            state: CSRF protection token (generated by caller)
            redirect_uri: Callback URL after authorization

        Returns:
            Full authorization URL with all required parameters

        Example:
            https://accounts.google.com/o/oauth2/v2/auth?
                client_id=...&
                redirect_uri=...&
                response_type=code&
                scope=openid%20email%20profile&
                state=...
        """
        pass

    @abstractmethod
    async def exchange_code_for_tokens(self, code: str, redirect_uri: str) -> OAuthTokens:
        """
        Exchange authorization code for OAuth tokens.

        Args:
            code: Authorization code from OAuth callback
            redirect_uri: Same redirect_uri used in authorization request

        Returns:
            OAuthTokens with access_token, id_token, refresh_token

        Raises:
            ValueError: Invalid code or network error
        """
        pass

    @abstractmethod
    async def verify_token(self, id_token: str) -> TokenClaims:
        """
        Verify and decode ID token (JWT).

        Args:
            id_token: JWT from OAuth provider

        Returns:
            TokenClaims with user identifier and metadata

        Raises:
            ValueError: Invalid token, expired, or signature verification failed

        Note:
            Must verify signature, expiration, audience, and issuer.
        """
        pass

    @abstractmethod
    async def get_user_info(self, access_token: str) -> OAuthUserInfo:
        """
        Fetch user information from provider's UserInfo endpoint.

        Args:
            access_token: Valid OAuth access token

        Returns:
            OAuthUserInfo with user profile data

        Raises:
            ValueError: Invalid token or network error

        Note:
            Used to enrich user profile with provider-specific metadata.
        """
        pass

    @abstractmethod
    async def refresh_access_token(self, refresh_token: str) -> OAuthTokens:
        """
        Refresh expired access token using refresh token.

        Args:
            refresh_token: Valid refresh token

        Returns:
            New OAuthTokens with refreshed access_token

        Raises:
            ValueError: Invalid refresh token or network error

        Note:
            Optional for MVP - can return NotImplementedError if not supported.
        """
        pass
