/**
 * pdf_generator/runner.js
 *
 * Fixed Puppeteer wrapper — NOT generated by LLM.
 * Reads a complete HTML document from stdin, renders it via headless Chrome,
 * and writes raw PDF bytes to stdout.
 *
 * Usage (called by NodePuppeteerRunner):
 *   echo "<html>...</html>" | node runner.js
 *
 * Exit codes:
 *   0 — success, PDF bytes on stdout
 *   1 — failure, error message on stderr
 */

const puppeteer = require('puppeteer');

async function main() {
    let html = '';
    for await (const chunk of process.stdin) {
        html += chunk;
    }

    if (!html.trim()) {
        process.stderr.write('runner.js: no HTML received on stdin\n');
        process.exit(1);
    }

    const browser = await puppeteer.launch({
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
        ],
    });

    try {
        const page = await browser.newPage();
        await page.setContent(html, { waitUntil: 'networkidle0' });

        const pdf = await page.pdf({
            format: 'A4',
            printBackground: true,
            preferCSSPageSize: true,
        });

        process.stdout.write(pdf);
    } finally {
        await browser.close();
    }
}

main().catch((err) => {
    process.stderr.write(String(err) + '\n');
    process.exit(1);
});
